version: '3.8'

services:
  nginx:
    image: nginx:latest  # Official Nginx image
    container_name: nginx_container
    env_file:
      - .env
    ports:
      - "80:80"  # Map port 80 on the host to port 80 on the container
      - "${NGINX_HO_PORT}:443"  # Map port 443 for HTTPS
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d  # Mount custom Nginx config
      - ./nginx/certificates:/etc/nginx/certificates  # For SSL certificates (optional)
      - ./nginx/logs:/var/log/nginx  # Log directory
    networks:
      - app_network

networks:
  app_network:
